In [1]:
import numpy as np
from numpy.random import RandomState, SeedSequence, MT19937, Generator

from nonparametric_ica_python import ICA


In [2]:
import matlab.engine
eng=matlab.engine.start_matlab()

In [3]:

M = 100
N = 10000
K = 3
rng = Generator(MT19937(1))
R_true = rng.random((M,K))
W_true = rng.exponential(1,(K,N))
X = R_true@W_true + 0.1*rng.normal(size=(M,N))
X_zero_mean_rows = X - X.mean(axis=1,keepdims=True)
U,S,V = np.linalg.svd(X_zero_mean_rows,full_matrices=False)
V = V.T # consistent w/ Matlab
Rpca = U[:,range(K)] @ np.diag(S[range(K)])
Wpca = V[:,range(K)].T



In [4]:
ica = ICA(K)
R_python,W_python,_,__ = ica.nonparametric_ica(X)

In [5]:
np.histogram(X[0,:])

(array([3079, 4370, 1817,  532,  149,   41,   10,    1,    0,    1]),
 array([-0.10586238,  0.93313702,  1.97213643,  3.01113583,  4.05013524,
         5.08913464,  6.12813404,  7.16713345,  8.20613285,  9.24513225,
        10.28413166]))

In [6]:
eng.addpath("../nonparametric-ica") 


'/home/dskrill/Documents/MATLAB:/usr/local/MATLAB/R2021a/toolbox/matlab/validators:/usr/local/MATLAB/R2021a/toolbox/matlab/elfun:/usr/local/MATLAB/R2021a/toolbox/matlab/elmat:/usr/local/MATLAB/R2021a/toolbox/matlab/capabilities:/usr/local/MATLAB/R2021a/toolbox/matlab/polyfun:/usr/local/MATLAB/R2021a/toolbox/matlab/sparfun:/usr/local/MATLAB/R2021a/toolbox/matlab/randfun:/usr/local/MATLAB/R2021a/toolbox/matlab/matfun:/usr/local/MATLAB/R2021a/toolbox/matlab/general:/usr/local/MATLAB/R2021a/toolbox/matlab/timefun:/usr/local/MATLAB/R2021a/toolbox/matlab/funfun:/usr/local/MATLAB/R2021a/toolbox/matlab/mvm:/usr/local/MATLAB/R2021a/toolbox/matlab/specfun:/usr/local/MATLAB/R2021a/toolbox/matlab/iofun:/usr/local/MATLAB/R2021a/toolbox/matlab/datafun:/usr/local/MATLAB/R2021a/toolbox/matlab/ops:/usr/local/MATLAB/R2021a/toolbox/matlab/datatypes:/usr/local/MATLAB/R2021a/toolbox/matlab/lang:/usr/local/MATLAB/R2021a/toolbox/matlab/strfun:/usr/local/MATLAB/R2021a/toolbox/matlab/strfun/validators:/usr/loc

In [34]:
R_matlab,W_matlab,_,__ = eng.nonparametric_ica(matlab.double(X.tolist()),3, 10,False,2,nargout=4)

In [8]:
R_matlab = np.array(R_matlab)

In [9]:
R_matlab.shape

(100, 3)

In [24]:
Wpca.shape

(3, 10000)

In [25]:
ica = ICA(K)
ica.maximize_negentropy_via_rotation(Wpca)[0][:,range(10)]

array([[-0.00078158, -0.00916079, -0.0036653 ,  0.06007747, -0.00654374,
         0.02458953, -0.00662317, -0.0008707 , -0.00750405, -0.00222164],
       [-0.00502404, -0.00377478, -0.00692283,  0.01389421,  0.00506755,
        -0.00011603, -0.00128237, -0.00930677, -0.00772332, -0.008113  ],
       [-0.00189949,  0.00523797,  0.00642472, -0.00197286, -0.00865389,
         0.00992196, -0.00411213,  0.00242879,  0.00900776, -0.04763931]])

In [26]:
np.array(eng.maximize_negentropy_via_rotation(matlab.double(Wpca.tolist()),10,2,False,nargout=4)[0])[:,range(10)]

array([[-0.0018063 ,  0.00530377,  0.00655064, -0.00220861, -0.00874869,
         0.00993119, -0.00409002,  0.00260059,  0.00914671, -0.04748151],
       [ 0.00069872,  0.00910179,  0.00355674, -0.05984545,  0.00661939,
        -0.02458164,  0.00659879,  0.0007212 ,  0.0073837 ,  0.00205837],
       [ 0.0050704 ,  0.00382527,  0.00686118, -0.01482861, -0.00479943,
        -0.000467  ,  0.00146569,  0.00927307,  0.00767587,  0.00902936]])

In [13]:
ica.entropy(X[0,:])

(1.218201697408917,
 0.0,
 0.00792588842451368,
 [-0.10638193054750361, 10.284651209428379, 100])

In [14]:
np.allclose(np.array(eng.histogram(matlab.double(X[0,:].tolist()),nargout=3)[0][0]).astype(int),
            ica.histogram(X[0,:])[0])

True

In [15]:
R_python

array([[ 1.28576262,  0.92342362,  0.42856649],
       [ 0.29103674,  1.50699473,  0.94674937],
       [ 0.76299099,  0.28001005,  0.85752315],
       [ 1.30315163,  0.68147636,  0.49805467],
       [ 0.1190624 ,  1.56487608,  0.05379937],
       [ 0.10822291,  0.31118318,  1.08501485],
       [ 1.71512967,  1.30735282,  0.08520068],
       [ 0.57841062,  1.10777141,  1.73713082],
       [ 0.98662577,  0.1526063 ,  0.14093332],
       [ 0.72680083,  0.22248389,  1.27137392],
       [ 1.7385385 ,  1.57355491,  1.74608055],
       [ 0.36115041,  1.61544365,  0.167071  ],
       [ 1.52590618,  1.48029618,  0.79544756],
       [ 1.33871663,  1.47682025,  0.48819721],
       [ 1.33565198,  0.82100658,  0.10654395],
       [ 1.22720026,  0.17393558,  0.48807994],
       [ 1.2303919 ,  0.3098257 ,  0.42859799],
       [ 1.40122712,  1.33298982,  0.16853388],
       [ 0.32985354,  0.40021301,  1.40017216],
       [ 0.14284864,  0.60623209,  0.72031429],
       [ 1.23465786,  0.45020902,  1.620

In [29]:
np.array(W_matlab)[0,range(10)]

array([0.28785063, 0.36593732, 0.18096381, 1.42835387, 0.8813257 ,
       0.59576157, 0.50721867, 0.03655642, 0.13450016, 0.06637848])

In [36]:
np.array(W_matlab)[:,range(10)]

array([[0.65571156, 0.26457979, 0.19598837, 0.67784311, 1.03761876,
        0.0100209 , 0.78134113, 0.41328425, 0.05317618, 3.16834752],
       [0.51399506, 0.0456027 , 0.35468727, 3.88876507, 0.18397336,
        1.9231381 , 0.1851219 , 0.51274194, 0.14137011, 0.43820737],
       [0.29269521, 0.3671918 , 0.1855523 , 1.48325937, 0.88321032,
        0.62399938, 0.50836614, 0.04124796, 0.13680909, 0.05582913]])

In [31]:
W_python[1,range(10)]

array([0.29702357, 0.3718043 , 0.18336195, 1.42946696, 0.90110428,
       0.59081621, 0.52099916, 0.04066004, 0.1354449 , 0.11211877])

In [16]:
R_matlab

array([[ 0.92857645,  0.4290843 ,  1.28235426],
       [ 1.50520563,  0.96234016,  0.29171918],
       [ 0.27394223,  0.8508455 ,  0.76706459],
       [ 0.6843991 ,  0.49442534,  1.30130374],
       [ 1.57391796,  0.07612933,  0.11256383],
       [ 0.29988076,  1.08347927,  0.11555889],
       [ 1.32075563,  0.08940125,  1.70626503],
       [ 1.09487063,  1.74030622,  0.58661586],
       [ 0.15562491,  0.13384559,  0.98483386],
       [ 0.21075924,  1.26213189,  0.73460344],
       [ 1.56785566,  1.74601109,  1.7421297 ],
       [ 1.62431982,  0.18747704,  0.35480272],
       [ 1.48509624,  0.80047342,  1.52258082],
       [ 1.48470555,  0.49631829,  1.33331841],
       [ 0.82977684,  0.10664176,  1.32991803],
       [ 0.17368549,  0.47750138,  1.2276085 ],
       [ 0.31113484,  0.4203339 ,  1.22972546],
       [ 1.34426799,  0.1754864 ,  1.39366961],
       [ 0.38636741,  1.39649149,  0.33888279],
       [ 0.60136926,  0.7247062 ,  0.14585169],
       [ 0.43745938,  1.60867164,  1.243

In [17]:
import cProfile

In [20]:
#cProfile.run('ica.nonparametric_ica(X)',sort='tottime')

         577771 function calls (545481 primitive calls) in 1.159 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.264    0.264    1.132    1.132 nonparametric_ica_python.py:77(maximize_negentropy_via_rotation)
    10731    0.210    0.000    0.549    0.000 nonparametric_ica_python.py:22(histogram)
    10731    0.157    0.000    0.811    0.000 nonparametric_ica_python.py:50(entropy)
    59094    0.131    0.000    0.131    0.000 {method 'reduce' of 'numpy.ufunc' objects}
64851/32561    0.115    0.000    0.248    0.000 {built-in method numpy.core._multiarray_umath.implement_array_function}
    10731    0.057    0.000    0.057    0.000 {method 'round' of 'numpy.ndarray' objects}
    10784    0.052    0.000    0.052    0.000 {method 'astype' of 'numpy.ndarray' objects}
        3    0.025    0.008    0.025    0.008 linalg.py:1482(svd)
    16221    0.014    0.000    0.014    0.000 {built-in method numpy.array}
     53

In [21]:
#%timeit ica.nonparametric_ica(X)
#%timeit R_matlab,W_matlab,_,__ = eng.nonparametric_ica(matlab.double(X.tolist()),3, 10,nargout=4)


In [22]:
R_python

array([[ 1.28576262,  0.92342362,  0.42856649],
       [ 0.29103674,  1.50699473,  0.94674937],
       [ 0.76299099,  0.28001005,  0.85752315],
       [ 1.30315163,  0.68147636,  0.49805467],
       [ 0.1190624 ,  1.56487608,  0.05379937],
       [ 0.10822291,  0.31118318,  1.08501485],
       [ 1.71512967,  1.30735282,  0.08520068],
       [ 0.57841062,  1.10777141,  1.73713082],
       [ 0.98662577,  0.1526063 ,  0.14093332],
       [ 0.72680083,  0.22248389,  1.27137392],
       [ 1.7385385 ,  1.57355491,  1.74608055],
       [ 0.36115041,  1.61544365,  0.167071  ],
       [ 1.52590618,  1.48029618,  0.79544756],
       [ 1.33871663,  1.47682025,  0.48819721],
       [ 1.33565198,  0.82100658,  0.10654395],
       [ 1.22720026,  0.17393558,  0.48807994],
       [ 1.2303919 ,  0.3098257 ,  0.42859799],
       [ 1.40122712,  1.33298982,  0.16853388],
       [ 0.32985354,  0.40021301,  1.40017216],
       [ 0.14284864,  0.60623209,  0.72031429],
       [ 1.23465786,  0.45020902,  1.620

In [23]:
R_matlab

array([[ 0.92857645,  0.4290843 ,  1.28235426],
       [ 1.50520563,  0.96234016,  0.29171918],
       [ 0.27394223,  0.8508455 ,  0.76706459],
       [ 0.6843991 ,  0.49442534,  1.30130374],
       [ 1.57391796,  0.07612933,  0.11256383],
       [ 0.29988076,  1.08347927,  0.11555889],
       [ 1.32075563,  0.08940125,  1.70626503],
       [ 1.09487063,  1.74030622,  0.58661586],
       [ 0.15562491,  0.13384559,  0.98483386],
       [ 0.21075924,  1.26213189,  0.73460344],
       [ 1.56785566,  1.74601109,  1.7421297 ],
       [ 1.62431982,  0.18747704,  0.35480272],
       [ 1.48509624,  0.80047342,  1.52258082],
       [ 1.48470555,  0.49631829,  1.33331841],
       [ 0.82977684,  0.10664176,  1.32991803],
       [ 0.17368549,  0.47750138,  1.2276085 ],
       [ 0.31113484,  0.4203339 ,  1.22972546],
       [ 1.34426799,  0.1754864 ,  1.39366961],
       [ 0.38636741,  1.39649149,  0.33888279],
       [ 0.60136926,  0.7247062 ,  0.14585169],
       [ 0.43745938,  1.60867164,  1.243